# Generated by Django 3.0.3 on 2020-05-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Dean', models.CharField(max_length=128)),
                ('Location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Age', models.PositiveIntegerField()),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sisya', to='cbv_app.Skool')),
            ],
        ),
    ]
